import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/future/image";
import styles from "../styles/Home.module.css";
import React from "react";
import HotelItem from "../components/HotelItem/HotelItem";
import SortAlpha from "../components/Icons/SortAlpha";
import Currency from "../components/Icons/Currency";
import Star from "../components/Icons/Star";
import SortItem from "../components/SortItem/SortItem";

const hotelItemList = [
  {
    id: 1,
    title: "Iberostar Grand Salomé",
    location: "Costa Teguise, Lanzarote, Spain",

    rating: 4,
    image: "/assets/hotel-image-1.png",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    cta: {
      title: "Book now",
      amount: 100,
    },
  },
  {
    id: 2,
    title: "Alua Atlántico Golf Resort",
    location: "Lara, Antalya, Turkey",

    rating: 5,
    image: "/assets/hotel-image-2.png",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    cta: {
      title: "Book now",
      amount: 200,
    },
  },
  {
    id: 3,
    title: "Las Piramides Resort",
    location: "Ayia Napa, Larnaca, Cyprus",
    rating: 3,
    image: "/assets/hotel-image-3.png",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    cta: {
      title: "Book now",
      amount: 300,
    },
  },
];
const sortItemList = [
  {
    id: 1,
    label: "alphabetically",
    icon: <SortAlpha />,
    active: true,
  },
  {
    id: 2,
    label: "price",
    icon: <Currency />,
    active: false,
  },
  {
    id: 3,
    label: "rating",
    icon: <Star />,
    active: false,
  },
];

const Home: NextPage = () => {
  const [hotelItems, setHotelItems] = React.useState(hotelItemList);
  const [readMore, setReadMore] = React.useState(false);
  const [sortItems, setSortItems] = React.useState(sortItemList);

  const sortByParam = (sortBy: string) => {
    return hotelItems.sort((a, b) => {
      if (sortBy === "alphabetically") {
        return a.title.localeCompare(b.title);
      } else if (sortBy === "price") {
        return a.cta.amount - b.cta.amount;
      } else if (sortBy === "rating") {
        return a.rating - b.rating;
      }
    });
  };
  const onSortItemClick = (id: number) => {
    const newSortItems = sortItems.map((item) => {
      if (item.id === id) {
        return { ...item, active: true };
      }
      return { ...item, active: false };
    });
    const sortedResult = sortByParam(newSortItems[id - 1].label);
    console.log(sortedResult);
    setHotelItems(sortedResult);

    setSortItems(newSortItems);
  };

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className="grid">
          <div className={`${styles.card} `}>
            <ul className={styles.sortNav}>
              {sortItems.map((item) => (
                <SortItem
                  key={item.id}
                  {...item}
                  onClick={() => {
                    onSortItemClick(item.id);
                  }}
                />
              ))}
            </ul>
          </div>
          <div className={`${styles.card} span-2`}>
            {hotelItems.map((hotelItem) => (
              <HotelItem key={hotelItem.id} {...hotelItem} />
            ))}
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
